### ISSUE TITLE
Format doesn't work

### ISSUE THREAD

**Issue by Cons-Cat** [creatorrr/emacs-mint-mode#5] opened 2021-11-16 16:36 UTC
When I save a file, I get this error:
```
Mint - Formatting files
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
I was looking for a pattern that contains ".mint" files,
such as "source/**/*.mint". Got "/home/conscat/documents/projects/test_project/source/Main.mint" instead.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
All done in 3.277ms!
```
Running ``mint format`` on my command line works correctly.

**Comment by zw963** [comment] 2022-06-29 15:54
This have another side effect.

When i want to close emacs window, get following error message:

```
Save file /tmp/mint-format-errors-fileJRkt7U (buffer *prettier errors*)? (y, n, !, ., q, C-r, C-f, d or C-h) 
```

it should be a mode manage buffer, should not mention user to save it.

**Comment by zw963** [comment] 2022-06-29 16:03
You can comment [this](https://github.com/creatorrr/emacs-mint-mode/blob/master/mint-mode.el#L269) line, to close auto format,
and wait this issue get fix.

and, you can leave the emacs builtin format feature, you need set indentation to 2

```cl
(add-hook 'mint-mode-hook (lambda ()
                            (setq-local js-indent-level 2)
                            ))

```

**Comment by zw963** [comment] 2022-07-01 11:23
BTW: i consider this issue caused by `mint format` will return code 1 if current file formatted by command instead.

i consider this probably a design error,  `mint format --check` exactly do this things, instead, if `mint format` run
sucessful, whatever formatted file no not, it should return code 0 always.

**Comment by zw963** [comment] 2022-07-03 14:22
I fix this in #6 , though, because the issue from upstream mint-lang, i have to workaround the return code 1 as successful becuuse [this issue](https://github.com/mint-lang/mint/issues/548)

**Comment by lassik** [comment] 2022-07-04 21:39
You should probably depend on [reformatter.el](https://github.com/purcell/emacs-reformatter) to call the code formatter.

Or just rely on format-all.el and apheleia.el to cover it.

**Comment by zw963** [comment] 2022-07-05 06:28
> You should probably depend on [reformatter.el](https://github.com/purcell/emacs-reformatter) to call the code formatter.
> 
> Or just rely on format-all.el and apheleia.el to cover it.

Yes, i stolen the code from the format-all.el, use it to locate the project root.
but, it seem like use it directly not work, i don't know how to change default directory for those packages.

**Comment by jgarte** [comment] 2022-09-11 11:13
Hi all, I'm closing this issue since it was fixed in https://github.com/creatorrr/emacs-mint-mode/pull/6

Feel free to reopen if you need to discuss formatting further.

**Closed as completed by jgarte** 2022-09-11 11:13 UTC
