### ISSUE TITLE
Use reformatter.el

### ISSUE THREAD

**Issue by lassik** [creatorrr/emacs-mint-mode#10] opened 2022-09-11 12:28 UTC
The current `mint-format-file` function is barely working copy/paste code.

**Comment by lassik** [comment] 2022-09-11 12:28
https://github.com/purcell/emacs-reformatter

**Comment by jgarte** [comment] 2022-09-11 17:10
I like this idea. I recently started using some packages that depend on `reformatter.el` and they work excellently.

@lassik Would you be interested in submitting a PR for that?

The other option is to add the formatting feature to an external formatting collection package that leverages `emacs-reformatter` and we remove `mint-format-file` here in `emacs-mint-mode`, then mention that formatter collection package in the `README`.

`emacs-mint-mode` would then be dedicated mostly to syntax highlighting while eglot/lsp-mode provides completions/other lsp features and this emacs formatter collection package would include the formatting that shells out to `mint format`.

The downside to that approach is that people would then have to install that formatting collection package to get formatting for mint instead of having it provided all in one place. The upside is that it would hand over the maintenance burden of that formatting feature to those package maintainers and focus `emacs-mint-mode` primarily on providing syntax highlighting.


@lassik @zw963 wdyt

**Comment by zw963** [comment] 2022-09-12 06:34
How to use `reformatter.el` with mint-mode? could you please share your's config?

In fact, i do some investigation before, but it not work for me.

i thought the issue is:

1. `mint format` return the wrong exit code. https://github.com/mint-lang/mint/issues/548
2. `mint format`  can't find the correct root folder. https://github.com/purcell/emacs-reformatter/issues/37

**Comment by jgarte** [comment] 2022-09-13 02:16
@zw963 I haven't used `reformatter.el` for mint-mode. I've only seen it used with python in this package: https://github.com/nasyxx/emacs-python-isort/blob/master/python-isort.el

**Comment by jgarte** [comment] 2022-09-13 04:28
@zw963 `eglot-format` is working for me with eglot in a mint file. I'm wondering if we should not support formatting in emacs-mint-mode since the language servers already do and the current implementation is buggy. What do you think?

**Comment by lassik** [comment] 2022-09-13 04:50
> I'm wondering if we should not support formatting in emacs-mint-mode since the language servers already do and the current implementation is buggy. What do you think?

That makes sense. I can also add support to [format-all](https://github.com/lassik/emacs-format-all-the-code).

**Comment by zw963** [comment] 2022-09-13 08:20
> @zw963 `eglot-format` is working for me with eglot in a mint file. I'm wondering if we should not support formatting in emacs-mint-mode since the language servers already do and the current implementation is buggy. What do you think?

AFAIK, most of mode i used, support use a function like `format-buffer` to format buffer.

```cl
(defun format-buffer ()
  "Perform a bunch of operations of a buffer."
  (interactive)
  (untabify (point-min) (point-max))
  (whitespace-cleanup)
  (indent-region (point-min) (point-max))
  )
```

So,  probably doesn't really need a separate formatting tool.

However, if the language itself supports formatting commands, many modes still support it with a functions, although, Mint's own formatting commands have bugs for now.

format-all by is really a very good options if @lassik can add support for it anyway.

**Comment by jgarte** [comment] 2022-09-13 23:47
> > I'm wondering if we should not support formatting in emacs-mint-mode since the language servers already do and the current implementation is buggy. What do you think?
> 
> That makes sense. I can also add support to [format-all](https://github.com/lassik/emacs-format-all-the-code).

@lassik That sounds great! Keep us posted.

@zw963 Here's another mode the uses reformatter.el:

https://github.com/jcollard/elm-mode/blob/master/elm-format.el#L26

**Comment by jgarte** [comment] 2022-10-28 19:42
@creatorrr @zw963 @lassik 

Does anyone have any objections if I were to remove the formatting code in `emacs-mint-mode` since it is already covered by the mint language server?

That would allow `emacs-mint-code` to narrow it's scope to just syntax highlighting.

The current formatter in `emacs-mint-mode` is also buggy.

I think we should also not support autocompletion since that is handled by mint lsp.

See this PureScript emacs package for similar project scope:

https://github.com/purefunctor/purs-mode/

WDYT?

**Comment by creatorrr** [comment] 2022-10-29 00:57
Sounds good to me

**Comment by zw963** [comment] 2022-10-29 05:58
Yes,  i consider buffer feature is not need too.

In fact, there are so many package to same things, recent, i add the Crystal lang support to [apheleia](https://github.com/radian-software/apheleia/pull/137), which is a auto-format package run in the after-save-hook instead of before-save-hook, for better performance.

I want to add mint-mode support too, but no luck, same issue as the emacs-mint-mode builtin,  https://github.com/mint-lang/mint/issues/549#issuecomment-1295331332,  mint format can't find the correct position of mint.json, i thought this issue can be fixed by upstream, but, no response for now.

for autocompletion, i don't understand what need to remove.

**Comment by jgarte** [comment] 2022-10-31 04:20
Hi, I'm closing this issue as formatting and auto completion will be provided by `mint ls`.

**Closed as completed by jgarte** 2022-10-31 04:20 UTC
